// Copyright (c) 2021 rookie-ninja
//
// Use of this source code is governed by an Apache-style
// license that can be found in the LICENSE file.

package clear

import (
	"github.com/rookie-ninja/rk/common"
	"github.com/urfave/cli/v2"
	"os"
)

// Clear remove target/ folder
func Clear() *cli.Command {
	command := &cli.Command{
		Name:      "clear",
		Usage:     "Clear target folder generated by rk build",
		UsageText: "rk clear",
		Action:    clearAction,
	}

	return command
}

// Clear target/ folder
func clearAction(ctx *cli.Context) error {
	chain := common.NewActionChain()
	chain.Add("Clearing target folder", func(ctx *cli.Context) error {
		return os.RemoveAll(common.BuildTarget)
	}, false)

	return chain.Execute(ctx)
}
